issuer: http://localhost:5556/dex

storage:
  type: memory

web:
  http: 0.0.0.0:5556

staticClients:
- id: kiwi-app
  redirectURIs:
  - 'http://localhost:4000/auth/callback'
  name: 'Kiwi App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0

logger:
  level: "debug"
  format: "text" # can also be "json"

staticPasswords:
- email: "a@a.pl"
  # bcrypt hash of the string "password"
  hash: "$2a$10$2b2cU8CPhOTaGrs1HRQuAueS7JTT5ZHsHSzYiFPm1leZck7Mc8T4W"
  username: "admin"
  userID: "08a8684b-db88-4b73-90a9-3cd1661f5466"

enablePasswordDB: true